# -*- coding: utf-8 -*-
"""My Module.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F5DqiFO5-VhJyx2oDTLSA_M7kh_PCMqW
"""

def say_hi(name):
  return ('hi '+name)

def say_bye(name):
  return ('Bye '+name)

